--MENAMPILKAN SEMUA DATA DAN KOLOM TABEL DOSEN
SELECT * FROM Dosen;

--TAMPILKAN DATA TABEL DOSEN DENGAN HANYA MENAMPILKAN KOLOM NAMA DOSEN
SELECT NamaDosen From Dosen;

--TAMPILKAN NAMA DOSEN SAJA DENGAN PRODI INFORMATIKA
SELECT NamaDosen FROM Dosen WHERE Prodi = 'Informatika';

--TAMPILKAN NAMA DOSEN YANG MENGAJAR BASIS DATA
SELECT D.NamaDosen
FROM Dosen D
INNER JOIN MataKuliah MK ON D.DosenID = MK.DosenID
WHERE MK.NamaMK = 'Basis Data'

--TAMPILKAN NAMA DOSEN YANG MENGAJAR BASIS DATA (SUBQUERY)
SELECT NamaDosen
FROM Dosen
WHERE DosenID = (
	SELECT DosenID
	FROM MataKuliah
	WHERE NamaMK = 'Basis Data'
)

--TAMPILKAN MATA KULIAH YANG DIAJAR OLEH Agus Hidayat, M.Kom (SUBQUERY)
SELECT NamaMK
FROM MataKuliah
WHERE DosenID = (
	SELECT DosenID
	FROM Dosen
	WHERE Dosen.NamaDosen = 'Agus Hidayat, M.Kom'
)

--MENAMPILKAN MAHASISWA YANG MEMMILKI NILAI 'A'
SELECT NamaMahasiswa 
FROM Mahasiswa
WHERE MahasiswaID IN (
	SELECT MahasiswaID
	FROM Nilai
	WHERE NilaiAkhir = 'A'
)

--TAMPILKAN NILAI MATA KULIAH DENGAN NILAI AKHIR 'A'
SELECT NamaMK
FROM MataKuliah
WHERE MataKuliahID IN (
	SELECT MataKuliahID
	FROM Nilai
	WHERE NilaiAkhir = 'A'
)

--MENAMPILKAN DAFTAR PRODI YANG MAHASISWA-NYA > 2 (SUBQUERY)
SELECT Prodi, TotalMhs
FROM (
	SELECT Prodi, COUNT(*) AS TotalMhs
	FROM Mahasiswa
	GROUP BY Prodi
) AS HitungMhs
WHERE TotalMhs > 2;

--CREATE TABLE (SEMENTARA)
WITH MhsIF AS (
	SELECT * FROM Mahasiswa WHERE Prodi = 'Informatika'
)
SELECT * FROM MhsIF

--BUAT TABLE SEMENTARA UNTUK MENGHITUNG JUMLAH MAHASISWA PER PRODI
WITH MhsProdi AS (
	SELECT Prodi, COUNT(*) AS TotalMahasiswa
	FROM Mahasiswa
	GROUP BY Prodi
)
SELECT * FROM MhsProdi WHERE TotalMahasiswa > 2

--SET OPERATORS
--UNION : MENGGABUNGKAN DAFTAR NAMA DOSEN DAN DAFTAR NAMA MAHASISWA
SELECT NamaDosen FROM Dosen
UNION
SELECT NamaMahasiswa FROM Mahasiswa;

--UNION : MENGGABUNGKAN RUANGAN YANG KAPASITASNYA > 40 DAN YANG KAPASITASNYA < 40
SELECT KodeRuangan, Gedung, Kapasitas FROM Ruangan WHERE Kapasitas > 40
UNION
SELECT KodeRuangan, Gedung, Kapasitas FROM Ruangan WHERE Kapasitas < 40;

--IMTERSECT
--MENGGABUNGKAN MAHASISWA ID YANG ADA DI TABEL KRS DAN TABEL NILAI
SELECT MahasiswaID FROM KRS
INTERSECT
SELECT MahasiswaID FROM Nilai;

--MENGGABUNGKAN MataKuliahID YANG ADA DI TABEL MATA KULIAH DAN NILAI
SELECT MataKuliahID From MataKuliah
INTERSECT
SELECT MataKuliahID FROM Nilai;